config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :tasks, only: [:show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :reports do
    resources :comments, only: [:create, :destroy]
    get :mark_as_reported, on: :member
    post :add_report, on: :collection
  end
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                   }, path_prefix: 'auth'
  resources :users
  resources :tags

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'reports#index'

end

app/models/task.rb
# frozen_string_literal: true

class Task < ActiveRecord::Base
  STATUSES = %i[todo done backlog].freeze

  belongs_to :report
  has_one :author, through: :report, foreign_key: :user_id, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, as: :commentable, dependent: :destroy

  enum status: STATUSES
  # enum status: [:todo, :done, :backlog]

  accepts_nested_attributes_for :taggings, reject_if: :all_blank, allow_destroy: true

  validates :title, :description, :status, :tags, presence: true
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[edit update destroy]

  after_action :verify_authorized

  def show
    @task = Task.includes(comments: [:user, :commentable]).find(params[:id])

    authorize @task
    @commentable = @task
    @comment = Comment.new
  end

  def edit
    authorize @task
  end

  def update
    authorize @task
    if @task.update(permitted_attributes(@task))
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @task
    @report = @task.report
    @task.destroy

    redirect_to @report, notice: 'User was successfully destroyed.'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/tasks/_form.html.haml
= simple_form_for @task, html: { class: 'form-horizontal' } do |f|
  = f.error_notification

  = f.input :title
  = f.input :description
  = f.input :status, collection: Task::STATUSES, label_method: -> (task) { t("enums.task.status.#{task}") },
  include_blank: false
  = f.association :tags, collection: Tag.all, input_html: { class: 'task-tags-select', multiple: true }

  = f.button :submit, class: 'btn-primary'
  = link_to t('cancel'), users_path, class: 'btn btn-default'

app/views/tasks/_tags_block.html.haml
%p
  %strong= task.tags.map(&:name).join(', ')

app/views/tasks/_task.html.haml
%li.header
  %h5
    = link_to(task.title, task_path(task))

  %p
    = task.description
  = render 'tasks/tags_block', task: task
  %hr

app/views/tasks/edit.html.haml
.page-header
  %h1=t '.title'
= render partial: 'form'

app/views/tasks/show.html.haml
.page-header
  %h1=t '.title'

%h2.strong
  = @task.title

%p
  %strong= Task.human_attribute_name(:description)
  %br
%p
  = @task.description
%p
  %strong= Task.human_attribute_name(:status) + ':'
  %br
  -## TODO: move to presenter
  = t("enums.task.status.#{@task.status}")
= render 'tags_block', task: @task

%p= link_to(t('.back_to_report'), report_path(id: @task.report_id))

- if policy(@task).edit?
  = link_to t('edit'), edit_task_path(@task), class: 'btn btn-default'
- if policy(@task).destroy?
  = link_to t('destroy'), task_path(@task), method: :delete, data: { confirm: t('confirm') }, class: 'btn btn-danger'

-## TODO: dry it
%h5.strong
  = t('create_comment')
  = render 'comments/form'
  %hr

  %p
    = t('comments_list')
  = render @task.comments

app/views/tasks/update.html.haml
%h1 Tasks#update
%p Find me in app/views/tasks/update.html.haml