config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :tasks, only: [:show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :reports do
    resources :comments, only: [:create, :destroy]
    get :mark_as_reported, on: :member
    post :add_report, on: :collection
  end
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                   }, path_prefix: 'auth'
  resources :users
  resources :tags

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'reports#index'

end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ActiveRecord::Base
  include Stringify

  has_many :taggings
  has_many :tasks, through: :taggings

  validates :name, presence: true, uniqueness: true

  scope :by_name, ->(name) { where('name ilike ?', "%#{name}%") }
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]

  after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  has_scope :by_name, default: '', allow_blank: true, only: :index

  respond_to :json, :html
  def index
    authorize Tag
    @tags = apply_scopes(policy_scope(Tag), params).page(params[:page])

    respond_with(@tags)
  end

  def show
    authorize @tag
  end

  def new
    authorize Tag
    @tag = Tag.new
  end

  def edit
    authorize @tag
  end

  def create
    authorize Tag
    @tag = Tag.new(permitted_attributes(Tag))

    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @tag

    if @tag.update(permitted_attributes(@tag))
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @tag
    @tag.destroy

    redirect_to tags_url, notice: 'Tag was successfully destroyed.'
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/tags/_form.html.haml
= simple_form_for @tag, html: { class: 'form-horizontal' } do |f|
  = f.error_notification

  = f.input :name
  = f.button :submit, class: 'btn-primary'
  = link_to t('cancel'), tags_path, class: 'btn btn-default'

app/views/tags/_tag.html.haml
%tr
  %td= link_to tag.id, tag_path(tag)
  %td= tag.name
  %td=l tag.created_at
  %td
    - if policy(tag).edit?
      = link_to t('edit'), edit_tag_path(tag), class: 'btn btn-default btn-xs'
    - if policy(tag).destroy?
      = link_to t('destroy'), tag_path(tag), method: :delete,
      data: { confirm: t('confirm') }, class: 'btn btn-xs btn-danger'

app/views/tags/edit.html.haml
.page-header
  %h1=t '.title'
= render partial: 'form'

app/views/tags/index.html.haml
.page-header
  %h1=t '.title'
%table.table.table-striped
  %thead
    %tr
      %th= Tag.human_attribute_name(:id)
      %th= Tag.human_attribute_name(:name)
      %th= Tag.human_attribute_name(:created_at)
      %th=t '.actions'
  %tbody
    = render @tags
= paginate @tags, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered'

.row
  - if policy(Tag).new?
    = link_to t('.new'), new_tag_path, class: 'btn btn-primary'

app/views/tags/new.html.haml
.page-header
  %h1=t '.title'
= render partial: 'form'

app/views/tags/show.html.haml
.page-header
  %h1=t '.title'

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @tag.name


= link_to t('back'), tags_path, class: 'btn btn-default'
= link_to t('edit'), edit_tag_path(@tag), class: 'btn btn-default'
= link_to t('destroy'), tag_path(@tag), method: :delete,
data: { confirm: t('confirm') }, class: 'btn btn-danger'