config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :tasks, only: [:show, :edit, :update, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :reports do
    resources :comments, only: [:create, :destroy]
    get :mark_as_reported, on: :member
    post :add_report, on: :collection
  end
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                   }, path_prefix: 'auth'
  resources :users
  resources :tags

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'reports#index'

end

app/models/report.rb
# frozen_string_literal: true

class Report < ActiveRecord::Base
  include AASM

  REPORT_STATUSES = %i[draft reported].freeze

  belongs_to :user
  # maybe do not destroy dependent records?
  # TODO: mask as deleted dependent records
  has_many :tasks, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :task_comments, through: :tasks, source: :comments

  enum status: REPORT_STATUSES

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  validates :title, :tasks, :user, presence: true

  scope :by_search, (lambda do |term|
    eager_load(:user)
      .where("reports.title ilike :term OR \
              users.first_name ilike :term OR \
              users.last_name ilike :term OR \
              users.nickname ilike :term", term: "%#{term}%")
  end)

  scope :by_user, -> (user_id) { where(user_id: user_id) }

  aasm column: :status, enum: true do
    state :draft, initial: true
    state :reported

    event :report do
      transitions from: :draft, to: :reported, success: proc { update(reported_at: Time.zone.now.utc) }
    end
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy mark_as_reported]

  after_action :verify_authorized, except: :add_report
  after_action :verify_policy_scoped, only: :index

  has_scope :by_search, default: '', allow_blank: true, only: :index
  has_scope :by_user, only: :index

  def index
    authorize Report
    @reports = apply_scopes(policy_scope(Report), params).page(params[:page])
  end

  def show
    authorize @report
    @commentable = @report
    @comment = Comment.new
  end

  def new
    authorize Report

    @report = Report.new
    @report.tasks.build
  end

  def edit
    authorize @report
  end

  def create
    authorize Report

    @report = Report.new(permitted_attributes(Report))

    if @report.save
      Publish::ReportService.run(@report)
      redirect_to @report, notice: 'Report was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @report

    if @report.update(permitted_attributes(@report))
      redirect_to @report, notice: 'Report was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @report

    @report.destroy
    redirect_to reports_url, notice: 'Report was successfully destroyed.'
  end

  def mark_as_reported
    authorize @report
    Notifications::ReportReportedJob.perform_async(@report.id)
    if @report.may_report? && @report.report!
      flash[:success] = 'Reported successfully'
    else
      flash[:error] = 'Could not be reported'
    end

    redirect_to @report
  end

  # TODO: use react
  def add_report
    @report = Report.find(params[:report_id])
  end

  private

  def set_report
    @report = Report.includes(tasks: [:tags], comments: [:user, :commentable]).find(params[:id])
  end
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/views/reports/_form.html.haml
= simple_form_for @report, html: { class: 'form-horizontal', id: 'report-form' } do |f|
  = f.error_notification

  = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
  = f.input :title
  %h3
    Tasks
  #tasks
    = f.simple_fields_for :tasks do |task|
      = render 'task_fields', f: task
    .links
      = link_to_add_association 'add task', f, :tasks, { class: 'btn-sm btn-success' }

  = f.button :submit, class: 'btn-primary'
  = link_to t('cancel'), reports_path, class: 'btn btn-default'

app/views/reports/_report.html.haml
%tr{ class: (local_assigns[:need_highlight] ? 'success' : '') }
  %td= report.id
  %td= report.user
  %td= link_to(report.title, report_path(report))
  %td= t("enums.report.status.#{report.status}")
  %td=l report.created_at
  %td
    - if policy(report).edit?
      = link_to t('edit'), edit_report_path(report), class: 'btn btn-default btn-xs'
    - if policy(report).destroy?
      = link_to t('destroy'), report_path(report), method: :delete,
      data: { confirm: t('confirm') }, class: 'btn btn-xs btn-danger'

app/views/reports/_search_form.html.haml
= form_tag(reports_path, method: :get, remote: true, id: 'report_search_form') do
  = text_field_tag :by_search, params[:by_search], placeholder: 'Search'
  = select_tag :by_user, options_from_collection_for_select(User.all, :id, :name), include_blank: true
  = submit_tag 'Search', name: 'search'

app/views/reports/_task_fields.html.haml
.row
  .col-sm-10.col-sm-offset-1
    .nested-fields
      %hr
      = f.input :title
      = f.input :description
      -## TODO: use simple_form enums translation
      = f.input :status, collection: Task::STATUSES, label_method: -> (task) { t("enums.task.status.#{task}") }, include_blank: false
      = f.association :tags, collection: Tag.all, input_html: { class: 'task-tags-select', multiple: true }

      = link_to_remove_association 'remove task', f, { class: 'btn-xs btn-danger' }

app/views/reports/add_report.js.haml
- if @report.present?
  if($('#reports_table_body').length) {$('#reports_table_body').prepend("#{ escape_javascript(render partial: @report, locals: { need_highlight: true }) }");};

app/views/reports/edit.html.haml
.page-header
  %h1=t '.title'
= render partial: 'form'

app/views/reports/index.html.haml
= render 'search_form'

.page-header
  %h1=t '.title'
%table.table.table-striped
  %thead
    %tr
      %th= Report.human_attribute_name(:id)
      %th= Report.human_attribute_name(:user_id)
      %th= Report.human_attribute_name(:title)
      %th= Report.human_attribute_name(:status)
      %th= Report.human_attribute_name(:created_at)
      %th=t '.actions'
  %tbody#reports_table_body
    = render @reports

#reports_pagination
  = paginate @reports, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered'

.row
  = link_to t('.new'), new_report_path, class: 'btn btn-primary'

app/views/reports/index.js.haml
$('#reports_table_body').empty();
$('#reports_pagination').empty();
- if @reports.present?
  $('#reports_table_body').
  append("#{ escape_javascript(render partial: 'report', collection: @reports) }");

  $('#reports_pagination').
  append("#{ escape_javascript(paginate @reports, remote: true) }");

app/views/reports/new.html.haml
.page-header
  %h1=t '.title'
= render partial: 'form'

app/views/reports/show.html.haml
.page-header
  %h1=t('.title')
  %h3
    =t('.report_status_title')
    = t("enums.report.status.#{@report.status}")

%p
  %strong= Report.human_attribute_name(:user_id) + ':'
  %br
  = @report.user
%p
  %strong= Report.human_attribute_name(:title) + ':'
  %br
  = @report.title

%br
%h4
  Tasks
  %ul
    = render @report.tasks


= link_to t('.back'), reports_path, class: 'btn btn-default'

- if policy(@report).edit?
  = link_to t('.edit'), edit_report_path(@report), class: 'btn btn-default'

- if policy(@report).destroy?
  = link_to t('.destroy'), report_path(@report), method: :delete,
  data: { confirm: t('.confirm') }, class: 'btn btn-danger'

- if policy(@report).mark_as_reported?
  = link_to t('.form_report'), mark_as_reported_report_path(@report),
  data: { confirm: t('.confirm') }, class: 'btn btn-danger'

-## TODO: dry it
%h5.strong
  = t('create_comment')
  = render 'comments/form'
  %hr

  %p
    = t('comments_list')
  = render @report.comments